/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimeOfDay = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'afternoon' : IDL.Null,
});
export const Appointment = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'preferredTime' : TimeOfDay,
  'phoneNumber' : IDL.Text,
  'serviceNeeded' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const ProcedureRecord = IDL.Record({
  'doctorNotes' : IDL.Text,
  'cost' : IDL.Nat,
  'date' : IDL.Text,
  'procedureName' : IDL.Text,
  'receiptId' : IDL.Nat,
});
export const PatientProfile = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const Role = IDL.Variant({ 'patient' : IDL.Null, 'doctor' : IDL.Null });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctorPrincipal' : IDL.Func([IDL.Principal], [], []),
  'addProcedureRecord' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProcedures' : IDL.Func([], [IDL.Vec(ProcedureRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getPatientProcedures' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProcedureRecord)],
      ['query'],
    ),
  'getPatientProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPatientProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        TimeOfDay,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePatientProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimeOfDay = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'afternoon' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'preferredTime' : TimeOfDay,
    'phoneNumber' : IDL.Text,
    'serviceNeeded' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const ProcedureRecord = IDL.Record({
    'doctorNotes' : IDL.Text,
    'cost' : IDL.Nat,
    'date' : IDL.Text,
    'procedureName' : IDL.Text,
    'receiptId' : IDL.Nat,
  });
  const PatientProfile = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const Role = IDL.Variant({ 'patient' : IDL.Null, 'doctor' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctorPrincipal' : IDL.Func([IDL.Principal], [], []),
    'addProcedureRecord' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProcedures' : IDL.Func([], [IDL.Vec(ProcedureRecord)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getPatientProcedures' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProcedureRecord)],
        ['query'],
      ),
    'getPatientProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPatientProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          TimeOfDay,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePatientProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };