/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'fullName' : string,
  'email' : string,
  'message' : [] | [string],
  'preferredDate' : string,
  'preferredTime' : TimeOfDay,
  'phoneNumber' : string,
  'serviceNeeded' : string,
}
export interface PatientProfile {
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'bloodGroup' : string,
  'notes' : string,
  'phone' : string,
  'allergies' : Array<string>,
}
export interface ProcedureRecord {
  'doctorNotes' : string,
  'cost' : bigint,
  'date' : string,
  'procedureName' : string,
  'receiptId' : bigint,
}
export type Role = { 'patient' : null } |
  { 'doctor' : null };
export type TimeOfDay = { 'morning' : null } |
  { 'evening' : null } |
  { 'afternoon' : null };
export interface UserProfile {
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'bloodGroup' : string,
  'notes' : string,
  'phone' : string,
  'allergies' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoctorPrincipal' : ActorMethod<[Principal], undefined>,
  'addProcedureRecord' : ActorMethod<
    [Principal, string, string, bigint, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProcedures' : ActorMethod<[], Array<ProcedureRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getPatientProcedures' : ActorMethod<[Principal], Array<ProcedureRecord>>,
  'getPatientProfile' : ActorMethod<[Principal], [] | [PatientProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerPatientProfile' : ActorMethod<
    [string, string, string, string, string, Array<string>, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAppointment' : ActorMethod<
    [string, string, string, string, TimeOfDay, string, [] | [string]],
    undefined
  >,
  'updatePatientProfile' : ActorMethod<
    [string, string, string, string, string, Array<string>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];