/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TimeOfDay = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'afternoon' : IDL.Null,
});
export const Appointment = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'preferredTime' : TimeOfDay,
  'phoneNumber' : IDL.Text,
  'serviceNeeded' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'submitAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        TimeOfDay,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TimeOfDay = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'afternoon' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'preferredTime' : TimeOfDay,
    'phoneNumber' : IDL.Text,
    'serviceNeeded' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'submitAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          TimeOfDay,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };