/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Appointment {
    fullName: string;
    email: string;
    message?: string;
    preferredDate: string;
    preferredTime: TimeOfDay;
    phoneNumber: string;
    serviceNeeded: string;
}
export enum TimeOfDay {
    morning = "morning",
    evening = "evening",
    afternoon = "afternoon"
}
export interface backendInterface {
    getAllAppointments(): Promise<Array<Appointment>>;
    submitAppointment(fullName: string, phoneNumber: string, email: string, preferredDate: string, preferredTime: TimeOfDay, serviceNeeded: string, message: string | null): Promise<void>;
}
import type { Appointment as _Appointment, TimeOfDay as _TimeOfDay } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: TimeOfDay, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointment(arg0, arg1, arg2, arg3, to_candid_TimeOfDay_n7(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointment(arg0, arg1, arg2, arg3, to_candid_TimeOfDay_n7(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TimeOfDay_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeOfDay): TimeOfDay {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    email: string;
    message: [] | [string];
    preferredDate: string;
    preferredTime: _TimeOfDay;
    phoneNumber: string;
    serviceNeeded: string;
}): {
    fullName: string;
    email: string;
    message?: string;
    preferredDate: string;
    preferredTime: TimeOfDay;
    phoneNumber: string;
    serviceNeeded: string;
} {
    return {
        fullName: value.fullName,
        email: value.email,
        message: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.message)),
        preferredDate: value.preferredDate,
        preferredTime: from_candid_TimeOfDay_n5(_uploadFile, _downloadFile, value.preferredTime),
        phoneNumber: value.phoneNumber,
        serviceNeeded: value.serviceNeeded
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
}): TimeOfDay {
    return "morning" in value ? TimeOfDay.morning : "evening" in value ? TimeOfDay.evening : "afternoon" in value ? TimeOfDay.afternoon : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function to_candid_TimeOfDay_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOfDay): _TimeOfDay {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOfDay): {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
} {
    return value == TimeOfDay.morning ? {
        morning: null
    } : value == TimeOfDay.evening ? {
        evening: null
    } : value == TimeOfDay.afternoon ? {
        afternoon: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
